### ISSUE TITLE
Use react-highlight more semantic.

### ISSUE THREAD

**Issue by jessy1092** [akiran/react-highlight#1]
I want to use component more semantic.

The common usage is:
```html
<Highlight className='language-name-of-snippet'>
  {"code snippet to be highlighted"}
</Highlight>
```

If I want to use Javascript. Maybe it can use like:
```js
var JS = require('react-highlight').JS;
```
```html
<JS>
  {"code snippet to be highlighted"}
</JS>
```
It is more semantic and doesn't write the className.   :)

**Comment by akiran** [comment]
What do you mean by performance impact ?
Do you mean that file size will be larger or code runtime to detect language ?

As of now I observe that webpack is bundling the code required for highlighting all the languages and which is causing file size to be > 100KB.

In general we only need syntax highlighting for few languages.
I am trying to add support for a build step that lets users to include only languages they require.

**Comment by jessy1092** [comment]
Yap, I agree we only need syntax highlighting for few languages. 
I saw this commit 9d981b62085efd7a42bf3fd3da4293d025b93123 . It's the nice way for specific language :+1:

**Comment by akiran** [comment]
It is still experimental.  It uses dynamic require statement
https://github.com/akiran/react-highlight/blob/master/optimized.jsx#L19-21.
It is working well with webpack.
But browserify doesn't  support dynamic requires .  How do we handle this in browserify ?

**Comment by DylanPiercey** [comment]
Perhaps separate languages into individual components/files. This way you could require only the languages you need.

```javascript
let JS = require('react-highlight/js');
let HTML = require('react-highlight/html');
let CSS = require('react-highlight/css');
``` 

It would also be hugely convenient to pre pack the css for each language into the component so that style sheets are not required.

**Comment by ianwalter** [comment]
Imho, this optimization is much more important than support for browserify. In my case, the size difference was over 400kB!
