### ISSUE TITLE
Problem during installing due to unmet peer dependency

### ISSUE THREAD

**Issue by Vinnl** [akiran/react-highlight#10]
$ npm install react-highlight --save
    npm WARN install Couldn't install optional dependency: Unsupported
    redux@0.1.0 /home/rs55df/Workspace/redux
    ├── UNMET PEER DEPENDENCY highlight.js@^8.4.x
    └── react-highlight@0.5.1 
    
    npm WARN EPEERINVALID react-highlight@0.5.1 requires a peer of highlight.js@^8.4.x but none was installed.
    npm WARN EPACKAGEJSON redux@0.1.0 No repository field.
    npm WARN EPACKAGEJSON redux@0.1.0 No license field.

I tried checking whether I could fix this myself, but I couldn't get the tests to run locally, encountering the same errors as in the build that is failing: https://travis-ci.org/akiran/react-highlight/builds/84639338

**Comment by akiran** [comment]
Fixed in react-highlight@0.7
