### ISSUE TITLE
Update highlight to 9.x.x

### ISSUE THREAD

**Issue by VladShcherbin** [akiran/react-highlight#19]

**Comment by will-hart** [comment]
This is a breaking issue for me on Windows due to https://github.com/isagalaev/highlight.js/issues/895 which was fixed in 9.4.0. Would you accept a pull request?

**Comment by jgunnison** [comment]
OS X here and I'm having a similar issue due to Webpack.
https://github.com/isagalaev/highlight.js/issues/895

**Comment by akiran** [comment]
Yes you can open a PR

**Comment by akiran** [comment]
Yes, Made a release with this change
