### ISSUE TITLE
How to import css

### ISSUE THREAD

**Issue by L3ARNING2B** [akiran/react-highlight#25]
> The styles will most likely be in node_modules/highlight.js/styles folder.

Why would I have a highlight.js in my `node_modules` if I have installed the package with 

    npm install react-highlight --save

Should I install in parallel `highlight.js` ? In your package.json, there is : 

```jsx
"dependencies": {
   "highlight.js": "^9.6.0"
}
```

Which means the package should be under `node_modules/react-highlight/node_modules/highlight.js/styles`

**Comment by firestar300** [comment]
@L3ARNING2B Do you have the answer ?
