### ISSUE TITLE
Use 'create-react-class' package instead of React.createClass

### ISSUE THREAD

**Issue by MichaelDeBoey** [akiran/react-highlight#29]
`React.createClass` has been deprecated and extracted to it's own package since [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings).

The following warning is displayed if that version of React is used:
`Warning: Highlight: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

See [Migrating from `React.createClass`](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass) to fix this.

This could be a temporary fix, but I think moving to ES6 classes is more appropriate :-)

**Comment by ivorafael** [comment]
+1

**Comment by aroc** [comment]
+1

**Comment by maksim-lunochkin** [comment]
@MichaelDeBoey
I think this repo isn't under support now.
May be you could create scoped package under your username?
https://docs.npmjs.com/getting-started/scoped-packages

**Comment by MichaelDeBoey** [comment]
@maksim-lunochkin I don't have the time to maintain the package, so I don't know if publishing a scoped package would be a good idea. 😕

**Comment by maksim-lunochkin** [comment]
@MichaelDeBoey I can maintain the package then.
I will take your version as a basis if you don't mind

**Comment by MichaelDeBoey** [comment]
@maksim-lunochkin You can go ahead and use my solution as the basis of your scoped package if you want 🙂

**Comment by maksim-lunochkin** [comment]
there is scoped package: https://www.npmjs.com/package/@maxlun86/react-highlight
