### ISSUE TITLE
dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by thierryc** [akiran/react-highlight#36]
Juste a suggestion for Syntax highlighting of mutiple code snippets.

Replace **innerHTML** into the next version by **dangerousInnerHTML**

```
<Highlight innerHTML={true}>
  {"html with multiple code snippets"}
</Highlight>

``` 

Like this:

```
<Highlight dangerousInnerHTML={true}>
  {"html with multiple code snippets"}
</Highlight>

``` 

or juste like this.

```
<Highlight dangerousInnerHTML>
  {"html with multiple code snippets"}
</Highlight>

```

**Comment by mbj36** [comment]
@thierryc We appreciate your suggestion, but currently we would not like to change prop name.
