### ISSUE TITLE
Dynamic content not highlighing

### ISSUE THREAD

**Issue by shalinibajpai0310** [akiran/react-highlight#44]
Hi,

Content which are loaded dynamically are only getting highlighted on page load . Content is not getting updated inside <Highlight></Highlight> when component is re-rendered .
![highlightreact](https://user-images.githubusercontent.com/20796527/31886900-df5257da-b813-11e7-88a9-1719b47928dc.PNG)

**Comment by mbj36** [comment]
@shalinibajpai0310  can you reproduce this issue on Codesandbox ?

Feel free to open new issue with link to sandbox
