### ISSUE TITLE
when do you support react 16?

### ISSUE THREAD

**Issue by ufoqhmdt** [akiran/react-highlight#45]
when do you support react 16?

**Comment by ufoqhmdt** [comment]
![image](https://user-images.githubusercontent.com/1751382/32761497-4ffa048c-c8b9-11e7-87b6-73bc6cf4d4dd.png)

**Comment by scko823** [comment]
there is a work around for now
https://github.com/akiran/react-highlight/issues/39#issuecomment-334898100

**Comment by mbj36** [comment]
@ufoqhmdt From the next release, which will be probably by today or tomorrow. Thanks!
