### ISSUE TITLE
ReactDomOption

### ISSUE THREAD

**Issue by kingykking** [akiran/react-highlight#47]
Module not found: Can't resolve 'react/lib/React' in 'D:\yyyfed\YYYFE\node_modules\.15.6.2@react-dom\lib

Module not found: Can't resolve 'react/lib/React' in 'D:\yyyfed\YYYFE\node_modules\.15.6.2@react-dom\lib'

**Comment by mbj36** [comment]
@kingykking Can you try our recent version`0.11.1`

This error was due to React 16, previously we didn;t support React 16
