### ISSUE TITLE
npm package missing compiled code

### ISSUE THREAD

**Issue by pawelgalazka** [akiran/react-highlight#53]
When you install react highlight by npm or yarn, `index.js` points to `lib/index.js` which does not exist. You need to probably make compiled code public. It seems that it relates only to `0.11.0` version.

**Comment by Tankpt** [comment]
same problem with above

**Comment by mbj36** [comment]
@pawelgalazka Thanks for the issue, I will update the package in a while

**Comment by mbj36** [comment]
@pawelgalazka @Tankpt We updated the package!
