### ISSUE TITLE
react-highlight not highlighting the code

### ISSUE THREAD

**Issue by jaapbakker88** [akiran/react-highlight#55]
I'm having an issue with this package where it's not highlighting the code I'm feeding it, or even applying the classes I expect it to give it. I've attached two images one of an error I'm getting in the console, and one of the generated HTML. 

I upgraded to the latest version and I'm running react 15.1. Is this a know issue or am I just missing somthing obvious.

<img width="1482" alt="screen shot 2018-04-11 at 10 32 20" src="https://user-images.githubusercontent.com/1172870/38605793-9eb97cee-3d74-11e8-820a-ff15abebd3b4.png">
<img width="837" alt="screen shot 2018-04-11 at 10 32 58" src="https://user-images.githubusercontent.com/1172870/38605794-9ecfba22-3d74-11e8-8ad1-d692a2e869c5.png">

**Comment by samblackk** [comment]
@jaapbakker88 Did you figure out what was causing this? I'm experiencing the same thing.

**Comment by jaapbakker88** [comment]
@samblackk I think we replaced the library with our custom solution, don't remember anything else about this.
