### ISSUE TITLE
Any plans to upgrade highlightjs dependency ? 

### ISSUE THREAD

**Issue by joelbandi** [akiran/react-highlight#77]
It seems the current `highlight.js` version has a vulnerability as outlined here: https://github.com/advisories/GHSA-7wwv-vh3v-89cq

If this is still planned for maintenance, I can issue a PR.

**Comment by arnozhang** [comment]
![image](https://user-images.githubusercontent.com/2292646/104595480-a4413580-56ad-11eb-9a27-bc4ad41f4e03.png)

**Comment by akiran** [comment]
Fixed it

**Comment by joelbandi** [comment]
Thank you!
