### ISSUE TITLE
Fix React v0.14.x warnings, use ReactDOM

### ISSUE THREAD

**Issue by kirjs** [akiran/react-highlight#8]
`Warning: Highlight.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.`

**Comment by marcelpanse** [comment]
Please accept pull-request to fix this:
https://github.com/akiran/react-highlight/pull/9

**Comment by iamblue** [comment]
@marcelpanse  , I do it ~
https://github.com/akiran/react-highlight/pull/11

**Comment by iamblue** [comment]
I also fixed the test env bugs

**Comment by kirjs** [comment]
Fixed in 0.6.1
